adam: True
lr: 0.0001
batch_size: 16

momentum: 0.9
weight_decay: 0.001
step_size: 5
gamma: 0.1
num_epoch: 30
early_stop: 100
test_batch_size: 32
valid_ratio: 0.2
use_grayscale: False

# selection for transform functions:
# 0: 'AutoContrast'
# 1: 'Equalize'
# 2: 'Rotate'
# 3: 'Posterize'
# 4: 'Color'
# 5: 'Contrast'
# 6: 'Brightness'
# 7: 'Sharpness'
# 8: 'ShearX'
# 9: 'ShearY'
# 10: 'CutoutAbs'
# 11: 'TranslateXabs'
# 12: 'TranslateYabs'
# Examples:K
  # ('Transform', min_val, max_val)
  # a augment list as [('AutoContrast', 0, 1), ('Equalize', 0.1, 1.9)] can be entered with:
# augment_list:
  # - 0,0,1
  # - 1,0.1,1.9
augment_list:
  - 0,0,1
  - 1,0.1,1.9
  - 2,0.1,1.9
  - 3,0.1,1.9
